main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name="home"),
  path("about/", views.about, name="about"),

  path("tech/", views.TechList.as_view(), name="tech_index"),
  path("tech/<int:pk>/add_usage", views.add_usage, name="add_usage"),
  path("tech/<int:tech_pk>/assoc_user/<int:user_pk>/", views.assoc_user, name="assoc_user"),
  path("tech/<int:pk>/", views.tech_detail, name="tech_detail"),
  path("tech/create/", views.TechCreate.as_view(), name="tech_create"),
  path("tech/<int:pk>/update", views.TechUpdate.as_view(), name="tech_update"),
  path("tech/<int:pk>/delete", views.TechDelete.as_view(), name="tech_delete"),

  path("users/", views.UsersList.as_view(), name="users_index"),
  path("users/<int:pk>/", views.UsersDetail.as_view(), name="users_detail"),
  path("users/create/", views.UsersCreate.as_view(), name="users_create"),
  path("users/<int:pk>/update", views.UsersUpdate.as_view(), name="users_update"),
  path("users/<int:pk>/delete", views.UsersDelete.as_view(), name="users_delete"),
]

tech_collector/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

# User Model
class User(models.Model):
  name = models.CharField(max_length=50)
  age = models.IntegerField()
  email = models.CharField(max_length=50)
  phone = models.CharField(max_length=10)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("users_detail", kwargs={ "pk": self.id })


# Tech Model
class Tech(models.Model):
  class Meta:
    ordering = ["name"] # order alphabetically

  name = models.CharField(max_length=50)
  brand = models.CharField(max_length=50)
  category = models.CharField(max_length=20)
  description = models.TextField(max_length=250)
  release_year = models.IntegerField("release year")
  purchase_date = models.DateField("purchase date")
  working = models.BooleanField(default=True)
  users = models.ManyToManyField(User)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("tech_detail", kwargs={ "pk": self.id })


# Usage Model
class Usage(models.Model):
  class Meta:
    ordering = ["-date"]

  date = models.DateField("last used")
  tech = models.ForeignKey(Tech, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.user} on {self.date}"

main_app/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import Usage

class UsageForm(ModelForm):
  # Meta object is needed for configuration
  class Meta:
    model = Usage
    fields = ["user", "date"]

main_app/views.py
from django.views.generic import (
  CreateView, 
  DeleteView, 
  DetailView, 
  ListView, 
  UpdateView,
)
from django.shortcuts import render, redirect
from .models import Tech, User
from .forms import UsageForm

# Create your views here.
def home(request):
  return render(request, "home.html")
def about(request):
  return render(request, "about.html")

def add_usage(request, pk):
  # instantiate a new form object using the key-value pairs from the post req
  form = UsageForm(request.POST)
  # check if the inputs are valid
  if form.is_valid():
    # create in-memory representation of the form object
    new_usage = form.save(commit=False)
    new_usage.tech_id = pk
    new_usage.save()
  return redirect("tech_detail", pk=pk)

def assoc_user(request, tech_pk, user_pk):
  Tech.objects.get(id=tech_pk).users.add(user_pk)
  return redirect("tech_detail", pk=tech_pk)

class TechList(ListView):
  model = Tech

# view function needed to add data from other models to the same page
def tech_detail(request, pk):
  tech_object = Tech.objects.get(id=pk)
  all_users = User.objects.all()
  # get the users that the tech doesn't belong to
  unlinked_users = User.objects.exclude(
    # exclude all users where user id is inside the tech's owner list
    id__in=tech_object.users.all().values_list("id")
  )
  # instantiate usage form to be rendered in template
  usage_form = UsageForm()
  return render(request, "main_app/tech_detail.html", { 
    "object": tech_object,
    "usage_form": usage_form,
    "all_users": all_users,
    "unlinked_users": unlinked_users,
  })
class TechCreate(CreateView):
  model = Tech
  # create a form using all fields in Model
  fields = [
    "name", "brand", "category", 
    "description", "release_year", 
    "purchase_date", "working"
  ]
class TechUpdate(UpdateView):
  model = Tech
  fields = ["name", "category", "description", "working"]
class TechDelete(DeleteView):
  model = Tech
  success_url = "/tech/"

class UsersList(ListView):
  model = User
class UsersDetail(DetailView):
  model = User
class UsersCreate(CreateView):
  model = User
  # create a form using all fields in Model
  fields = "__all__"
class UsersUpdate(UpdateView):
  model = User
  fields = ["age", "email", "phone"]
class UsersDelete(DeleteView):
  model = User
  success_url = "/users/"

main_app/templates/about.html
{% extends "base.html" %}

{% block content %}

  <h1>About the Tech Collector</h1>

  <hr />
  
  <div class="center-align">
    <p>
    Tech Collector provides an easy way to log all of your prized pieces of technology.
    </p>
    <p>
    Using the Tech Collector, you can log the different users of your tech and when they last used them. 
    </p>
    <p>
      You can also store the contact information for the users in case you need to reach out to them. 
    </p>
    <p>
      With the Tech Collector, you can see your usage habits and keep tabs on your tech!
    </p>
  </div>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <!-- load Materialize -->
    <!-- Compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <!-- Compiled and minified JavaScript -->
    <script 
      src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js">
    </script>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Tech Collector</title>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper cyan darken-3">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo">
                &nbsp;&nbsp;Tech Collector&nbsp;&nbsp;
              </a>
            </li>
          </ul>
          <ul class="right">
            <li>
              <a href="{% url 'about' %}">About</a>
            </li>
            <li>
              <a href="{% url 'tech_index' %}">View My Tech</a>
            </li>
            <li>
              <a href="{% url 'users_index' %}">View Users</a>
            </li>
            <li>
              <a href="{% url 'tech_create' %}">Add New Tech</a>
            </li>
            <li>
              <a href="{% url 'users_create' %}">Add New User</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">
      {% block content %} 
      {% endblock %}
    </main>
    <footer class="page-footer cyan darken-3">
      <p class="center-align">&copy; 2021 Tech Collector, All Rights Reserved</p>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends "base.html" %}

{% block content %}

  <h1>Home</h1>

  <hr>

  <div class="center-align">
    <h5>
      Welcome to the Tech Collector!
    </h5>
    <h5>
      Click the links in the navigation bar to get started!
    </h5>
  </div>
  
{% endblock %}

main_app/templates/main_app/tech_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Tech</h1>

  <h5>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h5>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Deletion" class="btn">
    <a href="{% url 'tech_detail' object.id %}" class="btn">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/tech_detail.html
{% extends "base.html" %}

{% block content %}

  <h1>Tech Details</h1>

  <div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ object.name }}</span>
          <p>Brand: {{ object.brand }}</p>
          <p>Category: {{ object.category }}</p>
          <p>Release Year: {{ object.release_year }}</p>
          <p>Purchase Date: {{ object.purchase_date }}</p>
          <p>Description: {{ object.description }}</p>
        {% if object.working %}
          <p class="green-text">Still working!!</p>
        {% else %}
          <p class="red-text">Oh no, it's broken!!</p>
        {% endif %}
        </div>
        <div class="card-action">
          <a href="{% url 'tech_update' object.id %}">Edit</a>
          <a href="{% url 'tech_delete' object.id %}">Delete</a>
        </div>
      </div>
    </div>
    <div class="col s6">
      <form action="{% url 'add_usage' object.id %}" method="post">
        {% csrf_token %}
        {{ usage_form.as_p }}
        <input type="submit" value="Add Usage Record" class="btn">
      </form>
      <table class="striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>User</th>
          </tr>
        </thead>
        <tbody>
          {% for usage in object.usage_set.all %}
          <tr>
            <td>{{ usage.date }}</td>
            <td>
              <a href="{% url 'users_detail' usage.user.id %}">
                {{ usage.user }}
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col s6">
        <h4 class="center-align">{{ object }}'s Users</h4>
    {% if object.users.count %}
      {% for user in object.users.all %}
        <div class="card">
          <a href="{% url 'users_detail' user.id %}">
            <div class="card-content">
              <span class="card-title">
                {{ user }}
              </span>
            </div>
          </a>
        </div>
      {% endfor %}
    {% else %}
        <h6 class="center-align">No users linked</h6>
    {% endif %}
    </div>
    <div class="col s6">
        <h4 class="center-align">Unlinked Users</h4>
    {% if unlinked_users.count %}
      {% for user in unlinked_users.all %}
        <div class="card">
          <a href="{% url 'users_detail' user.id %}">
            <div class="card-content">
              <span class="card-title">
                {{ user }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_user' object.id user.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
                <!-- <input type="submit" value="Add" class="btn"> -->
              </form>
            </div>
          </a>
        </div>
      {% endfor %}
    {% else %}
        <h6 class="center-align">{{ object.name }} has all users linked already.</h6>
    {% endif %}
    </div>
  </div>

  <script>
    const dateEl = $("#id_date");
    const selectEl = $("#id_user");

    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      default: new Date(),
      setDefault: true,
      autoClose: true,
    });
    M.FormSelect.init(selectEl);
  </script>

{% endblock %}

main_app/templates/main_app/tech_form.html
{% extends "base.html" %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Tech</h1>
{% endif %}

  <div class="card form-card">
    <form class="action="" method="post">
      <!-- csrf token needed to submit post requests -->
      {% csrf_token %} 
      <table>
        {{ form.as_table }}
      </table>
      <input class="btn mt-16" type="submit" value="Submit">
    </form>
  </div>

  <script>
    // cached element references
    const dateEl = $("#id_purchase_date");
    const checkboxEl = $("#id_working");
    const checkboxTdEl = checkboxEl.parent();
    const labelEl = $("<label />");

    // makes checkbox compatible with Materialize
    // need to wrap checkbox inside a label for it to be clickable
    checkboxTdEl.append(labelEl);
    checkboxEl.detach().appendTo(labelEl);
    checkboxEl.addClass("filled-in");
    labelEl.append("<span></span>");

    // add a materialize datepicker for purchase date UI
    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      default: new Date(),
      setDefault: true,
      autoClose: true
    })

  </script>

{% endblock %}

main_app/templates/main_app/tech_list.html
{% extends "base.html" %}

{% block content %}

  <h1>Tech List</h1>
  
{% for tech in object_list %}
  <div class="card">
    <a href="{% url 'tech_detail' tech.id %}">
      <div class="card-content">
        <span class="card-title">
          {{ tech.name }}
        </span>
        <div class="card-p">
          <p>Brand: {{ tech.brand }}</p>
          <p>Category: {{ tech.category }}</p>
          <p>Release Year: {{ tech.release_year }}</p>
          <p>Purchase Date: {{ tech.purchase_date }}</p>
          <p>Description: {{ tech.description }}</p>
        </div>
        {% if tech.working %}
          <p class="green-text">Still working!!</p>
        {% else %}
          <p class="red-text">Oh no, it's broken!!</p>
        {% endif %}
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/user_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete User</h1>

  <h5>
    Are you sure you want to remove 
    <span class="teal-text">{{ object.name }}</span>
    from the database?
  </h5>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Deletion" class="btn">
    <a href="{% url 'users_detail' object.id %}" class="btn">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/user_detail.html
{% extends "base.html" %}

{% block content %}

  <h1>User Details</h1>

  <div class="card">
    <div class="card-content">
      <span class="card-title">
        {{ object.name }}
      </span>
      <p>Age: {{ object.age }}</p>
      <p>Email: {{ object.email }}</p>
      <p>Phone: {{ object.phone }}</p>
    </div>
    <div class="card-action">
      <a href="{% url 'users_update' user.id %}">Edit</a>
      <a href="{% url 'users_delete' user.id %}">Delete</a>
    </div>
  </div>

{% endblock %}

main_app/templates/main_app/user_form.html
{% extends "base.html" %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add User</h1>
{% endif %}

  <div class="card form-card">
    <form class="action="" method="post">
      <!-- csrf token needed to submit post requests -->
      {% csrf_token %} 
      <table>
        {{ form.as_table }}
      </table>
      <input class="btn mt-16" type="submit" value="Submit">
    </form>
  </div>

{% endblock %}

main_app/templates/main_app/user_list.html
{% extends "base.html" %}

{% block content %}

  <h1>User List</h1>
  
{% for user in object_list %}
  <div class="card">
    <a href="{% url 'users_detail' user.id %}">
      <div class="card-content">
        <span class="card-title">
          {{ user.name }}
        </span>
        <div class="card-p">
          <p>Age: {{ user.age }}</p>
          <p>Email: {{ user.email }}</p>
          <p>Phone: {{ user.phone }}</p>
        </div>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/tech/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Tech Details</h1>

  <div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ object.name }}</span>
          <p>Brand: {{ object.brand }}</p>
          <p>Category: {{ object.category }}</p>
          <p>Release Year: {{ object.release_year }}</p>
          <p>Purchase Date: {{ object.purchase_date }}</p>
          <p>Description: {{ object.description }}</p>
        {% if object.working %}
          <p class="green-text">Still working!!</p>
        {% else %}
          <p class="red-text">Oh no, it's broken!!</p>
        {% endif %}
        </div>
        <div class="card-action">
          <a href="{% url 'tech_update' object.id %}">Edit</a>
          <a href="{% url 'tech_delete' object.id %}">Delete</a>
        </div>
      </div>
    </div>
    <div class="col s6">
      <form action="{% url 'add_usage' object.id %}" method="post">
        {% csrf_token %}
        {{ usage_form.as_p }}
        <input type="submit" value="Add Usage Record" class="btn">
      </form>
      <table class="striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>User</th>
          </tr>
        </thead>
        <tbody>
          {% for usage in object.usage_set.all %}
          <tr>
            <td>{{ usage.date }}</td>
            <td>{{ usage.user }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <script>
    const dateEl = $("#id_date");
    const selectEl = $("#id_user");

    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      default: new Date(),
      setDefault: true,
      autoClose: true,
    });
    M.FormSelect.init(selectEl);
  </script>
{% endblock %}